src/objects/Object1__c.object
<CustomObject>
    <fields>
        <fullName>Object_A__c</fullName>
        <label>Object_A</label>
        <referenceTo>Object_A__c</referenceTo>
        <relationshipLabel>Object1s</relationshipLabel>
        <relationshipName>Object1s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Object1</label>
    <nameField>
        <label>Object1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object1s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Object_A__c.object
<CustomObject>
    <label>Object_A</label>
    <nameField>
        <label>Object_A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object_As</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApexController.cls
public with sharing class ApexController{
    /*This will store the Id from the URL i.e., the Id of the Record that belongs to the Master Object.*/
    public String MasterRecordId        {get; set;}
    public List<Object1__c> ChildRecords  {get; set;}
    public List<Object_A__c> MasterRecord                 {get; set;}
    /*Constructor. This would build everything for our VF Page.*/
    public ApexController()
    {
        MasterRecordId = ApexPages.currentPage().getParameters().get('id');
        System.debug(MasterRecordId);
      
          
            /*Fetch the Master Record Details*/
            MasterRecord =
                [
                    SELECT 
                        Name
                    FROM
                        Object_A__c
                ];
           system.debug(MasterRecord);
            /*Fetch all the Child Records with respect to the Master Record. Note: Child_To_Parent_Lookup__c  is Lookup/M-D field on my Child SObject to the Parent – Master*/
            ChildRecords =
                [
                    SELECT 
                       Name
                    FROM
                        Object1__c
                    WHERE 
                        Object_A__c = :MasterRecordId
                ];
                system.debug(ChildRecords);
        
    }
}