src/objects/Object1__c.object
<CustomObject>
    <fields>
        <fullName>Object_A__c</fullName>
        <label>Object_A</label>
        <referenceTo>Object_A__c</referenceTo>
        <relationshipLabel>Object1s</relationshipLabel>
        <relationshipName>Object1s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Object1</label>
    <nameField>
        <label>Object1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object1s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Object_A__c.object
<CustomObject>
    <label>Object_A</label>
    <nameField>
        <label>Object_A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object_As</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Object_B__c.object
<CustomObject>
    <label>Object_B</label>
    <nameField>
        <label>Object_B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object_Bs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ObjectABController.cls
public with sharing class ObjectABController {

    public Boolean status { get; set; }

    
    /*This will store the Id from the URL i.e., the Id of the Record that belongs to the Master Object.*/
    public List<Object_A__c> MasterA {get; set;}
    public List<Object_B__c> MasterB {get; set;}
    //public string Aid{get; set;}
     //public Object1__c childob1 { get; set; }
     
     
    /*Constructor. This would build everything for our VF Page.*/
    public ObjectABController()
    {      
        String soql = 'select Name from Object_A__c where Name!= null';
        MasterA= Database.query(soql);           
        MasterB=[select Name from Object_B__c where Name!=null];
    }
    
   
/*
    public PageReference childA() {
    List<object1__c> childob1= new List<Object1__c>();
    MasterRecordId = ApexPages.currentPage().getParameters().get('id');
     childob1= [SELECT Name FROM Object1__c WHERE Object_A__c=:MasterRecordId];
        return Apexpages.currentPage();
    } 
*/
}