src/objects/Object1__c.object
<CustomObject>
    <fields>
        <fullName>Object_A__c</fullName>
        <label>Object_A</label>
        <referenceTo>Object_A__c</referenceTo>
        <relationshipLabel>Object1s</relationshipLabel>
        <relationshipName>Object1s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Object1</label>
    <nameField>
        <label>Object1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object1s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Object2__c.object
<CustomObject>
    <fields>
        <fullName>Object_A__c</fullName>
        <label>Object_A</label>
        <referenceTo>Object_A__c</referenceTo>
        <relationshipLabel>Object2s</relationshipLabel>
        <relationshipName>Object2s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Object2</label>
    <nameField>
        <label>Object2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object2s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Object3__c.object
<CustomObject>
    <fields>
        <fullName>Object_B__c</fullName>
        <label>Object_B</label>
        <referenceTo>Object_B__c</referenceTo>
        <relationshipLabel>Object3s</relationshipLabel>
        <relationshipName>Object3s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Object3</label>
    <nameField>
        <label>Object3 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object3s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Object4__c.object
<CustomObject>
    <fields>
        <fullName>Object_B__c</fullName>
        <label>Object_B</label>
        <referenceTo>Object_B__c</referenceTo>
        <relationshipLabel>Object4s</relationshipLabel>
        <relationshipName>Object4s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Object4</label>
    <nameField>
        <label>Object4 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object4s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Object_A__c.object
<CustomObject>
    <label>Object_A</label>
    <nameField>
        <label>Object_A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object_As</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Object_B__c.object
<CustomObject>
    <label>Object_B</label>
    <nameField>
        <label>Object_B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object_Bs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ObjectController.cls
public with sharing class ObjectController {

    
    /*attributes*/
    public Boolean StatusA {get; set;}
    public Boolean StatusB {get; set;}
    public List<Object_A__c> MasterA {get; set;}
    public List<Object_B__c> MasterB {get; set;}
     public Object_A__c  Adetails {get;set;}
     public Object_B__c  Bdetails {get;set;}
     public List<object1__c> a1details{get; set;}
     public List<object2__c> a2details{get; set;}
     public List<object3__c> b3details{get; set;}
     public List<object4__c> b4details{get; set;}
    public string Aid{get; set;}
    public string Bid{get; set;}
   
    /*Constructor. This would build everything for our VF Page.*/
    public ObjectController()
    {  
        statusA=false;
        statusB=false;
       MasterA= [select Id,Name from Object_A__c where Name!=null];
       MasterB=[select Name from Object_B__c where Name!=null];
       
    }
    
    /*pagereference action for master object A to fetch child object records*/
     public PageReference childA() {
      statusA=true;
      statusB=false;

     Adetails=[SELECT id,name FROM Object_A__c WHERE id =:Aid];
      
     a1details=[SELECT id,Name FROM Object1__c WHERE Object_A__c =:Aid];    
     a2details=[SELECT id,Name FROM Object2__c WHERE Object_A__c =:Aid];      
 
      return null;
    }

    /*pagereference action for master object B to fetch child objects records*/
    public PageReference childB() {
     statusA=false;
     statusB=true;

     Bdetails=[SELECT id,name FROM Object_B__c WHERE id =:Bid];
                  
        
     //b3details=[SELECT id,Name FROM Object3__c WHERE Object_B__c =:Bid];  
     b3details=new List<Object3__c>();
     for(Object3__c ob3:[SELECT id,Name FROM Object3__c WHERE Object_B__c =:Bid]){
        b3details.add(ob3);
     }  
     //b4details=[SELECT id,Name FROM Object4__c WHERE Object_B__c =:Bid];      
     b4details=new List<Object4__c>();
     for(Object4__c ob4:[SELECT id,Name FROM Object4__c WHERE Object_B__c =:Bid]){
        b4details.add(ob4);
     }  

        return null;
    }


   
   
}